task: teacher
data:
  model_name: root/private_data/luog/codex/Momo/infer/pretrained_mol/NovoMolGen_32M_SMILES_AtomWise/checkpoint-70000
  train_path: data/fda_train.jsonl
  val_path: data/fda_val.jsonl
  test_path: data/fda_test.jsonl
  batch_size: 8
  num_workers: 4
model:
  model_name: root/private_data/luog/codex/Momo/infer/pretrained_mol/NovoMolGen_32M_SMILES_AtomWise/checkpoint-70000
  lr: 2e-4
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  t_max: 1000
  eta_min: 1e-6
trainer:
  max_epochs: 10
  precision: bf16-mixed
  accelerator: gpu
  devices: [0]
  log_every_n_steps: 10
  accumulate_grad_batches: 4
  num_sanity_val_steps: 1
  strategy: ddp
  ddp_static_graph: false
  ddp_find_unused_parameters: true
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  monitor: val/loss
  monitor_mode: min
wandb:
  disabled: false
  project: Momo
  run_name: v1
  entity: "mllm-csu"
  api_key: "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"
  
runtime:
  output_dir: outputs/lightning_train
  seed: 56
  resume: false
  run_test: true
