name: proteinopd
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.8.0
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - pip:
      - accelerate==1.12.0
      - datasets==4.4.2
      - deepspeed
      - huggingface_hub
      - peft==0.18.0
      - pyyaml
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - tensorboard
      - tokenizers==0.22.2
      - tqdm
      - transformers==4.57.3
      - wandb
